# Generated by Django 3.2 on 2021-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsmodel',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
